[tool.autopep8]
max_line_length = 88
aggressive = 2

[tool.flake8]
max-line-length = 88
ignore = ["E203", "W503"]
extend-ignore = ["E203"]
exclude = [".git", "__pycache__", ".venv", "build", "dist"]

[tool.pytest.ini_options]
testpaths = ["python/tests"]
addopts = "-v --tb=short --strict-markers"
markers = [
    "slow: marks tests as slow",
    "integration: integration tests"
]