[tool.autopep8]
max_line_length = 88
aggressive = 2

[tool.flake8]
max-line-length = 88
ignore = ["E203", "W503"]
extend-ignore = ["E203"]
exclude = [".git", "__pycache__", ".venv", "build", "dist"]

[tool.pytest.ini_options]
testpaths = ["python/tests"]
addopts = "-v --tb=short --strict-markers"
markers = [
    "slow: marks tests as slow",
    "unit: unit tests (default, mock c++ library)",
    "integration: integration tests (require real c++ library)",
]

[tool.coverage.run]
source = ["python"]
omit = [
    "python/tests/*",
    "python/**/__init__.py",
]

[tool.coverage.report]
show_missing = true
skip_empty = true
exclude_lines = [
    "pragma: no cover",
    "if __name__ == '__main__':",
]