name: Build-Lint-Test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  # No 'packages' needed — we're using Docker Hub, not GHCR

jobs:
  build:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          target: test
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/process-command:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

  lint:
    name: Lint (C++ and Python)
    needs: build
    strategy:
      matrix:
        tool: [cpp, python]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull test image from Docker Hub
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/process-command:test

      - name: Run C++ linter
        if: matrix.tool == 'cpp'
        run: docker run --rm ${{ secrets.DOCKERHUB_USERNAME }}/process-command:test make -C build check-format

      - name: Run Python linter
        if: matrix.tool == 'python'
        run: docker run --rm ${{ secrets.DOCKERHUB_USERNAME }}/process-command:test flake8 python/ --count --show-source --statistics

  test:
    name: Test (C++ and Python)
    needs: build
    strategy:
      fail-fast: false
      matrix:
        suite: [cpp, python]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull test image from Docker Hub
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/process-command:test

      # ---------- C++ ----------
      - name: C++ tests & coverage
        if: always() && matrix.suite == 'cpp'
        run: |
          mkdir -p coverage-cpp
          chmod 777 coverage-cpp

          docker run --rm \
            -v "$PWD/coverage-cpp:/cov" \
            ${{ secrets.DOCKERHUB_USERNAME }}/process-command:test \
            bash -c '
              set -e
              mkdir -p /tmp/test-build
              cd /tmp/test-build
              cmake /app -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="--coverage" -DCMAKE_CXX_OUTPUT_EXTENSION_REPLACE=ON
              cmake --build . -j$(nproc)
              ctest -V

              # Optional: debug coverage data
              # find . -name "*.gcda"

              gcovr -r /app \
                    --filter /app/src/ \
                    --xml /cov/coverage.xml \
                    --html-details /cov/index.html
            '

      - name: Upload C++ coverage → Codecov
        if: always() && matrix.suite == 'cpp'
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage-cpp/coverage.xml
          flags: cpp
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload C++ coverage folder (artifact)
        if: always() && matrix.suite == 'cpp'
        uses: actions/upload-artifact@v4
        with:
          name: cpp-coverage
          path: coverage-cpp

      # ---------- Python ----------
      - name: Python tests & coverage
        if: always() && matrix.suite == 'python'
        run: |
          mkdir -p test-reports
          chmod 777 test-reports

          docker run --rm \
            -v "$PWD/test-reports:/app/python/reports" \
            ${{ secrets.DOCKERHUB_USERNAME }}/process-command:test \
            bash -c '
              set -e
              cd /app/python
              python3 -m coverage run -m pytest tests --junitxml=reports/junit.xml
              python3 -m coverage xml -o reports/coverage.xml
              python3 -m coverage html -d reports/htmlcov
            '

      - name: Upload Python coverage → Codecov
        if: always() && matrix.suite == 'python'
        uses: codecov/codecov-action@v4
        with:
          file: ./test-reports/coverage.xml
          flags: python
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload Python test-reports folder (artifact)
        if: always() && matrix.suite == 'python'
        uses: actions/upload-artifact@v4
        with:
          name: python-test-results
          path: test-reports

  run-example:
    name: Run example (smoke test)
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull test image from Docker Hub
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/process-command:test

      - name: Run example
        run: docker run --rm ${{ secrets.DOCKERHUB_USERNAME }}/process-command:test
