name: Build_Format_and_Tests

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize]
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Prepare local cache dir (if not restored)
        run: mkdir -p /tmp/.buildx-cache

      - name: Build Docker image with Buildx
        run: |
          docker buildx build \
            --tag process-command:test \
            --file Dockerfile \
            --cache-from=type=local,src=/tmp/.buildx-cache \
            --cache-to=type=local,dest=/tmp/.buildx-cache,mode=max \
            --output type=docker \
            .

      - name: Run C++ code linting
        run: |
          docker run --rm process-command:test \
            bash -c "cd /app/build && cmake --build . --target check-format"

      - name: Run Python code linting
        run: |
          docker run --rm process-command:test \
            flake8 python/ --count --show-source --statistics

      - name: Run C++ tests
        run: |
          docker run --rm process-command:test \
            bash -c "cd /app/build && ./test_process_command"

      - name: Run tests and generate JUnit XML
        run: |
          mkdir -p test-reports
          sudo chown 1000:1000 test-reports
          docker run --rm \
            -v $(pwd)/test-reports:/app/test-reports \
            process-command:test \`
            python3 -m pytest python/tests -v --tb=short --junitxml=/app/test-reports/test-results.xml

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-reports/test-results.xml

      - name: Run Python example
        run: |
          docker run --rm process-command:test
